import { useRouter } from 'next/router'
import Head from "next/head"
import React, { useEffect, useState } from 'react'
import Image from 'next/image'
import Logo from '@/svg/logo'
import Link from 'next/link'
import { useDatos } from "../context/Context";
import { AnimatePresence, motion } from "framer-motion";
import Footer from './footer'
import Wasa from '@/svg/wasa'



const Layout = ({ children }) => {

    const { loger, loader } = useDatos();

    const router = useRouter()

    const [raya, setRaya] = useState('conte')
    const [stroke, setStroke] = useState('')
    const [opa, setOpa] = useState('loader')
    // const [desmonte, setDesmonte] = useState(true)

    useEffect(() => {

        setTimeout(() => {
            setRaya('conte conteLleno')
            setStroke('stroke')
        }, 1);

        setTimeout(() => {
            setStroke('stroke fill')
        }, 4000);

        setTimeout(() => {
            setOpa('loader Noloader')
        }, 6000);

        setTimeout(() => {
            // setDesmonte(false)
            loader();
        }, 7000);


        // setTimeout(() => {
        //     loader();
        //   }, 3000);
    }, [])


    console.log(router.asPath)





    return (
        <>
            <Head>

                <meta charset="UTF-8"></meta>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

                <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>



                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />






            </Head>

            <header>
                <div class="top-bar">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <div class="d-inline-block">
                                    <span class="mai-mail fg-primary"></span> <a href="mailto:contact@mail.com">contact@mail.com</a>
                                </div>
                                <div class="d-inline-block ml-2">
                                    <span class="mai-call fg-primary"></span> <a href="tel:+0011223495">+0011223495</a>
                                </div>
                            </div>
                            <div class="col-md-4 text-right d-none d-md-block">
                                <div class="social-mini-button">
                                    <a href="#"><span class="mai-logo-facebook-f"></span></a>
                                    <a href="#"><span class="mai-logo-twitter"></span></a>
                                    <a href="#"><span class="mai-logo-youtube"></span></a>
                                    <a href="#"><span class="mai-logo-linkedin"></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <nav class="navbar navbar-expand-lg navbar-light">
                    <div class="container">
                        <Link href="/" class="navbar-brand">
                            <Logo class="logoPrin" />
                        </Link>

                        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse" id="navbarContent">
                            <ul class="navbar-nav ml-auto pt-3 pt-lg-0">
                                <li class={`nav-item ${router.asPath == '/' ? 'active' : ''}`}>
                                    <Link href="/" class="nav-link">Home</Link>
                                </li>
                                <li class={`nav-item ${router.asPath == '/about' ? 'active' : ''}`}>
                                    <Link href="/about" class="nav-link">About</Link>
                                </li>
                                <li class={`nav-item ${router.asPath == '/services' ? 'active' : ''}`}>
                                    <Link href="/services" class="nav-link">Services</Link>
                                </li>
                                <li class={`nav-item ${router.asPath == '/projects' ? 'active' : ''}`}>
                                    <Link href="/projects" class="nav-link">Projects</Link>
                                </li>
                                <li class={`nav-item ${router.asPath.includes('/blog') ? 'active' : ''}`}>
                                    <Link href="/blog" class="nav-link">Blog</Link>
                                </li>
                                <li class={`nav-item ${router.asPath == '/contact' ? 'active' : ''}`}>
                                    <Link href="/contact" class="nav-link">Contact</Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>


            </header>


            {children}

            <div class="back-to-top"></div>


            {
                loger && <div className={opa}>

                    <div className='bola1'>
                        <div className={raya} >

                        </div>
                    </div>

                    <Logo className={stroke} />

                </div>
            }

            <a href='#' target='_blank' className='wasa'>

                <Wasa />

            </a>


        </>
    )
}

export default Layout 